apiVersion: v1
kind: Service
metadata:
  name: hello-py-svc
spec:
  selector:
    app: hello-py
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-py
  name: hello-py
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - image: "rbroker/hello-py:22.12.22-151853"
        name: hello-py
        ports:
          - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config
          name: config
          readOnly: true       
      volumes:
      - configMap:
          defaultMode: 420
          name: hello-python-config
        name: config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-py-ingress
  labels:
    app: hello-py
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  - host: hello-argo.192.168.17.11.nip.io
    http:
      paths:
      - backend:
          service:
            name: hello-py-svc
            port:
              number: 6000
        path: /
        pathType: ImplementationSpecific