apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
        kind: build
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Configure container registry credentials
        kind: build
        id: dockerconfig
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: cloudbees-io/kaniko@v1
        name: Build a container image with Kaniko
        kind: build
        with:
          dockerfile: Dockerfile
          context: .
          destination: rbroker/hello-py:20240123
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1"
