apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        kind: build
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/kaniko@v1
        name: build and publish container image
        id: image-publish
        with:
          destination: rbroker/hello-py:20240123
  deploy:
    environment: DEV
    steps:
      - uses: cloudbees-io/ssh-deploy-actions@v1
        name: SSH with username and password
        kind: deploy
        with:
          host: rbroker.linkpc.net
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: "2022"
          script: |
            uname -a
            echo $HOME
            export HOME=/home/testusr
            cd $HOME
            echo "${{ vars.hello_python_yaml }}" > hello-python.yaml
            ls -Fla
            kubectl get namespaces
    needs:
      - build
